from dividends import get_summary_dividends_tax
from stocks import get_summary_stocks_tax

total_tax_to_paid_in_pln_dividends = get_summary_dividends_tax()
total_tax_to_paid_in_pln_stocks = get_summary_stocks_tax()
print(total_tax_to_paid_in_pln_dividends)
print(total_tax_to_paid_in_pln_stocks)